defaults:
  - exp_cfg
  - default_hydra
  - dataloader/cifar10@dataloader_cfg
  - _self_

exp_dir: results
devices: [0]
enable_wandb: true
seed: 0

model_cfg:
  backbone_cfg:
    hub_model_name: torchhub:resnet18
  loss_cfg:
    ntxent_loss_active: true
    ntxent_temp: 0.5

trainer_cfg:
  num_epochs: 1000
  use_amp: false
  optimizer_cfg:
    optimizer: Adam
    initial_lr: 0.003
    weight_decay: 1e-5
  scheduler_cfg:
    scheduler: LinearWarmupCosineAnnealingLR
    warmup_epochs: 10
  metric_logger_cfg:
    enable_wandb_logging: true
    enable_console_logging: true
    enable_local_figure_saving: true
    enable_optimizer_logging: true
    enable_collapse_logging: true
    enable_tsne_plot: true
    enable_log_spectra_plot: true

evaluator_cfg:
  knn_eval_cfg:
    enable_runner: true
    eval_freq: 100
  clustering_eval_cfg:
    enable_runner: true
    eval_freq: 100
  linear_probe_eval_cfg:
    use_for_best_checkpoint: true
    enable_runner: true
    eval_freq: 100
    num_epochs: 500