defaults:
  - exp_cfg
  - default_hydra
  - dataloader/cifar10_simclr@train_dataloader_cfg
  - dataloader/cifar10_simclr@eval_dataloader_cfg
  - header/simclr@model_cfg.header_cfg
  - _self_

exp_name: SimCLR
exp_dir: results
devices: [0, 1]

model_cfg:
  concat_different_views: false
  loss_cfg:
    ntxent_loss_active: true
    ntxent_temp: 0.5

trainer_cfg:
  num_epochs: 300
  use_amp: true
  optimizer_cfg:
    optimizer: LARS
    initial_lr: 1.2
    weight_decay: 1e-6
  scheduler_cfg:
    scheduler: CosineAnnealingLR
  metric_logger_cfg:
    enable_wandb_logging: false
    enable_console_logging: true
    enable_local_figure_saving: true
    enable_optimizer_logging: false
    enable_tsne_plot: true
    enable_log_spectra_plot: true

evaluator_cfg:
  eval_frequency: 10
eval_dataloader_cfg:
  collate_fn_cfg:
    collate_fn_type: NONE
  train: false
  shuffle: false
  batch_size: 256