defaults:
  - base_cifar10
  - dataloader/cifar100@train_dataloader_cfg
  - dataloader/cifar100@eval_dataloader_cfg
  - _self_

model_cfg:
  backbone_cfg:
    hub_model_name: torchhub:resnet18
eval_dataloader_cfg:
  collate_fn_cfg:
    collate_fn_type: NONE
  train: false
  shuffle: false
  batch_size: 512