defaults:
  - base
  - header/simclr@model_cfg.header_cfg
  - _self_

model_cfg:
  enable_momentum_network: true
  momentum_network_update_rate: 0.99
  header_cfg:
    header_name: MoCo
  loss_cfg:
    memory_bank_size: 4096