defaults:
  - base_cifar10
  - _self_

exp_name: NNCLR_CIFAR10
model_cfg:
  header_cfg:
    enable_proj_pred_header: true
    proj_pred_header_cfg:
      enable_nn_bank: true
  loss_cfg:
    ntxent_symmetric: true