defaults:
  - base
  - dataloader/stl10@dataloader_cfg  
  - _self_

exp_name: SimCLR_STL10
model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP
      enable_final_batchnorm: true
trainer_cfg:
  num_epochs: 2000
  optimizer_cfg:
    initial_lr: 0.002
