defaults:
  - base
  - dataloader/stl10@dataloader_cfg  
  - _self_

exp_name: simclr_stl10_mixup
model_cfg:
  header_cfg:
    enable_projection_header: false
    enable_mixup_augmentation: true
  loss_cfg:
    ntxent_loss_active: false
    ntxent_lie_loss_active: true
    ntxent_lie_loss_mse: true
    ntxent_lie_loss_weight: 1.0
    ntxent_lie_temp: 0.5
trainer_cfg:
  num_epochs: 2000
  optimizer_cfg:
    initial_lr: 0.002