defaults:
  - base
  - dataloader/stl10@train_dataloader_cfg
  - dataloader/stl10@eval_dataloader_cfg  
  - _self_

exp_name: SimCLR_STL10
model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP