defaults:
  - base
  - dataloader/tinyimagenet@dataloader_cfg
  - _self_

exp_name: SimCLR_TinyImageNet
model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP
trainer_cfg:
  optimizer_cfg:
    initial_lr: 0.002