defaults:
  - base
  - _self_

exp_name: cifar10_simclr
model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP
      output_dim: 128