defaults:
  - base
  - _self_

exp_name: simclr_cifar10_mixup
model_cfg:
  header_cfg:
    enable_projection_header: false
    enable_mixup_augmentation: true
  loss_cfg:
    ntxent_loss_active: false
    ntxent_lie_loss_active: true
    ntxent_lie_loss_mse: true
    ntxent_lie_loss_weight: 1.0
    ntxent_lie_temp: 0.5