defaults:
  - base
  - _self_

exp_name: SimCLR_CIFAR10
model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP
      output_dim: 64
      enable_final_batchnorm: true