defaults:
  - base
  - dataloader/tinyimagenet@dataloader_cfg
  - _self_

exp_name: tin_simclr_gaussaug
model_cfg:
  header_cfg:
    enable_projection_header: false
    enable_gaussian_augmentation: true
  loss_cfg:
    ntxent_loss_active: false
    ntxent_lie_loss_active: true
    ntxent_lie_loss_mse: true
    ntxent_lie_loss_weight: 1.0
    ntxent_lie_temp: 0.5
    ntxent_lie_z0_neg: true
trainer_cfg:
  optimizer_cfg:
    initial_lr: 0.002