defaults:
  - base_imagenet
  - _self_

exp_name: SimCLR_ImageNet
model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP