defaults:
  - base_cifar100
  - _self_

exp_name: SimCLR_CIFAR100
model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP