defaults:
  - base
  - dataloader/cifar100@train_dataloader_cfg
  - dataloader/cifar100@eval_dataloader_cfg
  - _self_

exp_name: SimCLR_CIFAR100
model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP