defaults:
  - transop_cifar10_simclr_laplacian_pretrain
  - _self_

exp_name: vi_20s_pretrain

trainer_cfg:
  num_epochs: 1000
model_cfg:
  header_cfg:
    projection_header_cfg:
      header_name: VICReg
      projection_type: MLP
      hidden_dim: 2048
      output_dim: 2048
  backbone_cfg:
    load_backbone: vicreg_mlp.pt
    freeze_backbone: true