defaults:
  - base
  - header/transop_header@model_cfg.header_cfg
  - dataloader/cifar10_ultraweak@train_dataloader_cfg
  - _self_

exp_name: TransOp

model_cfg:
  concat_different_views: false
  enable_header_momentum: false
  backbone_cfg:
    pretrained: true
    freeze_backbone: true
  loss_cfg:
    ntxent_loss_active: false
    ntxent_normalize: false
    ntxent_logit: cos
    kl_loss_active: true
    kl_loss_weight: 5.0e-3
    transop_loss_active: true
    transop_loss_weight: 1.0

trainer_cfg:
  optimizer_cfg:
    optimizer: Adam
    initial_lr: 0.0003
  scheduler_cfg:
    scheduler: CosineAnnealingLR
    warmup_epochs: 10
  metric_logger_cfg:
    enable_transop_logging: true
  use_amp: false
train_dataloader_cfg:
  batch_size: 256
devices: [0]

evaluator_cfg:
  knn_eval_cfg:
    eval_freq: 50
  clustering_eval_cfg:
    eval_freq: 50