defaults:
  - base_cifar10
  - _self_

exp_name: TransOp_NN_CIFAR10

model_cfg:
  header_cfg:
    enable_transop_header: true
    transop_header_cfg:
      dictionary_size: 200
      lambda_prior: 0.05
      transop_weight_decay: 1.0e-6
      transop_lr: 1.0e-3
      stable_operator_initialization: true
      detach_feature: false
      enable_nn_point_pair: true
      nn_memory_bank_size: 98304
      enable_splicing: true
      splice_dim: 64
      enable_variational_inference: true
      vi_cfg:
        scale_prior: 0.001
        distribution: Gaussian
        prior_type: Fixed
        per_iter_samples: 1
        total_samples: 1
        use_warmpup: false
        encode_features: true
        feature_dim: 512
        encoder_type: MLP
        variational_encoder_lr: 3.0e-4
        variational_encoder_weight_decay: 1.0e-5
  loss_cfg:
    ntxent_loss_active: true
    ntxent_normalize: true
    ntxent_logit: cos
    ntxent_detach_off_logit: false
    ntxent_symmetric: false
    kl_loss_active: true
    kl_loss_weight: 1.0e-5
    kl_weight_warmup: None
    transop_loss_active: true
    transop_loss_weight: 0.1

trainer_cfg:
  metric_logger_cfg:
    enable_transop_logging: true
  use_amp: false
  save_interval: 200