defaults:
  - transop_cifar10_nn
  - _self_

exp_name: TransOp_NN_CIFAR10_NNCLR

model_cfg:
  loss_cfg:
    ntxent_symmetric: true
  header_cfg:
    enable_proj_pred_header: true
    proj_pred_header_cfg:
      header_name: NNCLR
      enable_nn_bank: true
      nn_memory_bank_size: 65536