defaults:
  - transop_cifar10_nn
  - _self_

exp_name: TransOp_NN_CIFAR10_SimCLR

model_cfg:
  loss_cfg:
    ntxent_symmetric: true
    kl_loss_weight: 1.0e-5
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP
    enable_transop_augmentation: true
    transop_header_cfg:
      lambda_prior: 0.05
      vi_cfg:
        scale_prior: 0.001
        distribution: Gaussian+Gamma
        prior_type: Learned