defaults:
  - transop
  - header/transop_header@model_cfg.header_cfg
  - _self_

exp_name: TransOp-FISTA

model_cfg:
  loss_cfg:
    kl_loss_active: false
  header_cfg:
    enable_variational_inference: false
    projection_type: None
    projection_out_dim: 64
    enable_splicing: true
    splice_dim: 32
    fista_num_iterations: 800
    lambda_prior: 0.1
    transop_weight_decay: 1.0e-4
    transop_lr: 1.0e-3

trainer_cfg:
  optimizer_cfg:
    optimizer: SGD
    initial_lr: 0.0003
    enable_nesterov: true
  save_interval: 5
  metric_logger_cfg:
    loss_log_freq: 50
    transop_log_freq: 100
  scheduler_cfg:
    scheduler: CosineAnnealingLR
  use_amp: false
train_dataloader_cfg:
  batch_size: 64