defaults:
  - transop_nn_prediction
  - _self_

exp_name: TransOp-VI-NN-GammaLearn

model_cfg:
  loss_cfg:
    hyperkl_loss_active: true
    hyperkl_loss_weight: 1.0e-3
  header_cfg:
    lambda_prior: 0.2
    variational_inference_config:
      distribution: Gaussian+Gamma
      prior_type: Learned