defaults:
  - transop_fista
  - dataloader/cifar10_ultraweak@train_dataloader_cfg
  - _self_

exp_name: TransOp-FISTA-NN

model_cfg:
  header_cfg:
    enable_nn_point_pair: true
    nn_memory_bank_size: 98304