defaults:
  - transop
  - header/transop@model_cfg.header_cfg
  - _self_

exp_name: TransOpFISTA

model_cfg:
  loss_cfg:
    kl_loss_active: false
  header_cfg:
    enable_variational_inference: false
    fista_num_iterations: 300
    iter_variational_samples: 5
    lambda_prior: 0.2

trainer_cfg:
  metric_logger_cfg:
    loss_log_freq: 50
    transop_log_freq: 200