defaults:
  - base
  - header/transop@model_cfg.header_cfg
  - _self_

exp_name: TransOp

model_cfg:
  concat_different_views: false
  enable_header_momentum: true
  backbone_cfg:
    hub_model_name: resnet18
  loss_cfg:
    kl_loss_active: true
    kl_loss_weight: 0.01
    transop_loss_active: false
    transop_loss_weight: 1.0
    ntxent_temp: 0.1

trainer_cfg:
  optimizer_cfg:
    optimizer: LARS
    initial_lr: 0.3
  scheduler_cfg:
    scheduler: LinearWarmupCosineAnnealingLR
    warmup_epochs: 10
  metric_logger_cfg:
    enable_transop_logging: true
    transop_log_freq: 500
train_dataloader_cfg:
  batch_size: 256

evaluator_cfg:
  knn_eval_cfg:
    eval_freq: 50
  clustering_eval_cfg:
    eval_freq: 50