defaults:
  - transop_cifar10_nn_simclr_laplacian
  - _self_

exp_name: vi-20s-40refine-thresh0.1-infonce1e-2

trainer_cfg:
  num_epochs: 1000
  use_amp: false
model_cfg:
  loss_cfg:
    ntxent_loss_weight: 0.01
    kl_loss_weight: 1.0e-5
    kl_weight_warmup: None
    transop_loss_weight: 1.0
    transop_loss_fn: mse
    c_refine_loss_active: true
    c_refine_loss_weight: 10.0
  backbone_cfg:
    load_backbone: simclr_mlp.pt
  header_cfg:
    transop_header_cfg:
      start_iter: 0
      fine_tune_iter: 30000
      lambda_prior: 0.02
      enable_vi_refinement: true
      vi_refinement_lambda: 0.1
      fista_num_iterations: 40
      batch_size: 128
      vi_cfg:
        max_sample_start_iter: 0
        scale_prior: 0.02
        encode_point_pair: false
        enable_enc_attn: false