defaults:
  - transop_cifar10_nn_simclr_laplacian
  - _self_

exp_name: vi_20s_pretrain

trainer_cfg:
  num_epochs: 1000
model_cfg:
  backbone_cfg:
    load_backbone: simclr_mlp.pt
    freeze_backbone: true
  loss_cfg:
    ntxent_loss_active: false