defaults:
  - transop_base
  - _self_

exp_name: vi-A_prior-mse_ltemp5e-1_dict128_block64_thresh
devices: [0, 1, 2, 3]

model_cfg:
  header_cfg:
    transop_header_cfg:
      batch_size: 128
      dictionary_size: 128
      lambda_prior: 0.002
      vi_cfg:
        max_sample_start_iter: 5000
        samples_per_iter: 20
        total_num_samples: 20
        max_sample_l1_penalty: 0.0
  loss_cfg:
    ntxent_lie_temp: 0.5
    enable_shift_l2: true
    shift_l2_weight: 1.0e-2