defaults:
  - transop
  - header/transop_header@model_cfg.header_cfg
  - _self_

exp_name: TransOp-FISTA

model_cfg:
  loss_cfg:
    kl_loss_active: false
  header_cfg:
    enable_variational_inference: false
    fista_num_iterations: 300
    iter_variational_samples: 1
    lambda_prior: 0.15

trainer_cfg:
  save_interval: 5
  metric_logger_cfg:
    loss_log_freq: 50
    transop_log_freq: 200
  scheduler_cfg:
    scheduler: CosineAnnealingLR