defaults:
  - transop_nn
  - _self_

exp_name: TransOp-VI-NN-Prediction

model_cfg:
  loss_cfg:
    kl_loss_weight: 1.0e-3
    real_eig_reg_active: false
  header_cfg:
    projection_type: Linear
    projection_out_dim: 64
    lambda_prior: 0.04