defaults:
  - transop_base
  - _self_

exp_name: vi-B_prior-mse_ltemp5e-1_dict128_block64_thresh
devices: [0, 1]

dataloader_cfg:
  ssl_aug_cfg:
    enable_weak_z0_aug: false
  dataset_cfg:
    enable_nn_pair: true
    nn_pair_path: '../../results/pretrained/cifar10_cifar_nn.pt'
model_cfg:
  header_cfg:
    transop_header_cfg:
      batch_size: 256
      dictionary_size: 64
      lambda_prior: 0.005
      vi_cfg:
        enable_max_sampling: true
        max_sample_start_iter: 3000
        samples_per_iter: 20
        total_num_samples: 20
        max_sample_l1_penalty: 0.0
  loss_cfg:
    ntxent_lie_temp: 0.5
    ntxent_lie_loss_mse: false
    enable_shift_l2: true
    enable_prior_shift_l2: false
    shift_l2_weight: 5.0e-3