defaults:
  - base_cifar10
  - _self_

exp_name: TransOp_NN_CIFAR10

model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP
    enable_transop_header: true
    transop_header_cfg:
      batch_size: 128
      start_iter: 10000
      fine_tune_iter: 30000
      dictionary_size: 100
      lambda_prior: 0.02
      transop_weight_decay: 1.0e-5
      transop_lr: 0.01
      enable_variational_inference: true
      vi_cfg:
        max_sample_start_iter: 10000
        samples_per_iter: 20
        total_num_samples: 20
        max_sample_l1_penalty: 0.005
        feature_dim: 512
        scale_prior: 0.02
        variational_encoder_lr: 0.001
        variational_encoder_weight_decay: 1.0e-5

  loss_cfg:
    ntxent_loss_active: true
    ntxent_loss_weight: 0.1
    kl_loss_active: true
    kl_loss_weight: 1.0e-5
    kl_weight_warmup: Exponential
    shift_l2_active: false
    shift_l2_weight: 1.0e-2
    transop_loss_active: true
    transop_loss_weight: 1.0
    transop_loss_fn: mse

trainer_cfg:
  metric_logger_cfg:
    enable_transop_logging: true
  use_amp: false
  save_interval: 200
  enable_transop_grad_clip: true
  enable_coeffenc_grad_clip: true