defaults:
  - transop_base
  - dataloader/stl10@dataloader_cfg
  - _self_

exp_name: stl10_vi-A_prior-mse_ltemp5e-1_dict128_block64-direct
devices: [0, 1]

model_cfg:
  header_cfg:
    transop_header_cfg:
      enable_direct: true
      enable_block_diagonal: false

evaluator_cfg:
  semisup_probe_eval_cfg:
    manifold_aug: false
  aug_nn_eval_cfg:
    enable_runner: false
trainer_cfg:
  num_epochs: 2000
  optimizer_cfg:
    initial_lr: 0.002