defaults:
  - base
  - dataloader/tinyimagenet@dataloader_cfg
  - _self_

exp_name: cotrain_vi_100s

dataloader_cfg:
  ssl_aug_cfg:
    enable_weak_z0_aug: false
  dataset_cfg:
    enable_nn_pair: false
    nn_pair_path: '../../results/pretrained/cifar10_cifar_nn.pt'

model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP
      output_dim: 128
    enable_transop_augmentation: true
    enable_transop_header: true
    transop_header_cfg:
      batch_size: 128
      start_iter: 0
      fine_tune_iter: 0
      dictionary_size: 64
      lambda_prior: 0.01
      transop_weight_decay: 1.0e-2
      transop_lr: 0.001
      block_dim: 64
      enable_variational_inference: true
      vi_cfg:
        max_sample_start_iter: 0
        samples_per_iter: 50
        total_num_samples: 100
        max_sample_l1_penalty: 0.0
        feature_dim: 512
        scale_prior: 0.05
        shift_prior: 0.0
        variational_encoder_lr: 0.0001
        variational_encoder_weight_decay: 1.0e-5
        enable_learned_prior: true
        enable_prior_block_encoding: false
        enable_thresh_warmup: false
        enable_enc_attn: false
  loss_cfg:
    ntxent_loss_active: true
    ntxent_loss_weight: 1.0
    kl_loss_active: true
    kl_loss_weight: 1.0e-5
    kl_detach_shift: true
    kl_weight_warmup: Exponential
    enable_shift_l2: true
    shift_l2_weight: 1.0e-3
    transop_loss_active: true
    transop_loss_weight: 1.0
    transop_loss_fn: mse

trainer_cfg:
  metric_logger_cfg:
    enable_transop_logging: true
  optimizer_cfg:
    optimizer: AdamW
    initial_lr: 0.002
    weight_decay: 1e-5
    enable_nesterov: true
  use_amp: false
  save_interval: 100
  enable_transop_grad_clip: true
  enable_coeffenc_grad_clip: true
  enable_backbone_grad_clip: false
  enable_nn_queue: false