defaults:
  - transop_nn
  - _self_

exp_name: TransOp-VI-NN-GammaLearn

model_cfg:
  loss_cfg:
    hyperkl_loss_active: true
    hyperkl_loss_weight: 1.0e-1
  header_cfg:
    lambda_prior: 0.2
    vi_cfg:
      distribution: Gaussian+Gamma
      prior_type: Learned