defaults:
  - transop_base
  - dataloader/tinyimagenet@dataloader_cfg
  - _self_

exp_name: tin_vi_nn_dict128_kl1e-5_proj
devices: [0]

trainer_cfg:
  enable_nn_queue: true
  optimizer_cfg:
    initial_lr: 0.002
model_cfg:
  header_cfg:
    enable_projection_header: true
    transop_header_cfg:
      batch_size: 512
      dictionary_size: 128
      lambda_prior: 0.0
      transop_weight_decay: 1.0e-4
      vi_cfg:
        enable_max_sampling: false
        enable_prior_warmup: true
        prior_warmup_iters: 10000
  loss_cfg:
    ntxent_lie_temp: 0.5
    ntxent_lie_loss_mse: false
    ntxent_lie_z0_neg: false
    enable_shift_l2: false
    kl_loss_weight: 1.0e-5
    kl_weight_warmup: None
    transop_loss_weight: 10.0