defaults:
  - transop
  - dataloader/cifar10_ultraweak@train_dataloader_cfg
  - _self_

exp_name: TransOp-VI-NN

model_cfg:
  loss_cfg:
    kl_loss_weight: 1.0e-3
  header_cfg:
    lambda_prior: 0.05
    enable_nn_point_pair: true
    nn_memory_bank_size: 98304
    enable_splicing: true
    splice_dim: 32
    vi_cfg:
      per_iter_samples: 1
      total_samples: 1
      use_warmpup: false
      normalize_coefficients: false
      normalize_mag: 1.0
train_dataloader_cfg:
  batch_size: 256
trainer_cfg:
  save_interval: 20