defaults:
  - transop_nn
  - _self_

exp_name: TransOp-VI-NN-Prediction

model_cfg:
  header_cfg:
    projection_type: Linear
    projection_out_dim: 64
    lambda_prior: 0.3
    iter_variational_samples: 1
    total_variational_samples: 1
    transop_weight_decay: 1.0e-5
    transop_lr: 1.0e-4
trainer_cfg:
  scheduler_cfg:
    scheduler: CosineAnnealingLR
train_dataloader_cfg:
  batch_size: 256