defaults:
  - base_cifar10
  - _self_

exp_name: TransOp_NN_CIFAR10

model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: SimCLR
      projection_type: MLP
    enable_transop_header: true
    transop_header_cfg:
      start_iter: 2000
      fine_tune_iter: 50000
      dictionary_size: 100
      lambda_prior: 0.01
      transop_weight_decay: 1.0e-6
      transop_lr: 0.1
      enable_variational_inference: true
  loss_cfg:
    ntxent_loss_active: true
    ntxent_normalize: true
    ntxent_logit: cos
    ntxent_detach_off_logit: false
    ntxent_symmetric: false
    kl_loss_active: true
    kl_loss_weight: 1.0e-6
    kl_weight_warmup: None
    transop_loss_active: true
    transop_loss_weight: 0.5
    transop_loss_fn: mse

trainer_cfg:
  metric_logger_cfg:
    enable_transop_logging: true
  use_amp: false
  save_interval: 200