defaults:
  - base
  - _self_

exp_name: transop_contrastive
devices: [0]

model_cfg:
  header_cfg:
    enable_projection_header: false
    enable_transop_augmentation: true
    enable_transop_prior_grad: true
    enable_transop_header: true
    transop_header_cfg:
      batch_size: 256
      start_iter: 0
      fine_tune_iter: 0
      dictionary_size: 128
      lambda_prior: 0.0
      transop_weight_decay: 1.0e-3
      transop_lr: 0.001
      block_dim: 64
      enable_variational_inference: true
      vi_cfg:
        enable_max_sampling: false
        max_sample_start_iter: 0
        samples_per_iter: 10
        total_num_samples: 10
        max_sample_l1_penalty: 0.0
        feature_dim: 512
        scale_prior: 0.01
        shift_prior: 0.05
        variational_encoder_lr: 0.0001
        variational_encoder_weight_decay: 1.0e-5
        enable_learned_prior: true
        enable_prior_shift: true
        enable_prior_warmup: true
  loss_cfg:
    ntxent_loss_active: false
    ntxent_lie_loss_active: true
    ntxent_lie_loss_mse: true
    ntxent_lie_loss_weight: 1.0
    ntxent_lie_temp: 0.5
    kl_loss_active: true
    kl_loss_weight: 1.0e-5
    kl_detach_shift: false
    kl_weight_warmup: Exponential
    enable_shift_l2: false
    shift_l2_weight: 1.0e-2
    transop_loss_active: true
    transop_loss_weight: 1.0

trainer_cfg:
  metric_logger_cfg:
    enable_transop_logging: true
  use_amp: false
  enable_transop_grad_clip: true
  enable_coeffenc_grad_clip: true

evaluator_cfg:
  semisup_probe_eval_cfg:
    enable_runner: true
    eval_freq: 1000
  aug_nn_eval_cfg:
    enable_runner: true
    eval_freq: 100