defaults:
  - base
  - header/transop@model_cfg.header_cfg
  - _self_

exp_name: TransOp

model_cfg:
  concat_different_views: false
  backbone_cfg:
    hub_model_name: resnet18
  loss_cfg:
    kl_loss_active: true
    kl_loss_weight: 0.01
    ntxent_temp: 0.1

trainer_cfg:
  optimizer_cfg:
    optimizer: LARS
    initial_lr: 0.3
  metric_logger_cfg:
    enable_transop_logging: true
train_dataloader_cfg:
  batch_size: 256

evaluator_cfg:
  knn_eval_cfg:
    eval_freq: 25
  clustering_eval_cfg:
    eval_freq: 25
  linear_probe_eval_cfg:
    enable_runner: false