defaults:
  - transop_nn
  - _self_

exp_name: Gaussian_kl1e-3

model_cfg:
  header_cfg:
    lambda_prior: 0.05
    vi_cfg:
      scale_prior: 0.001
      distribution: Gaussian
      prior_type: Fixed