defaults:
  - transop_base
  - dataloader/stl10@dataloader_cfg
  - _self_

exp_name: stl10_vi-thresh_dict64
devices: [0, 1]

trainer_cfg:
  optimizer_cfg:
    initial_lr: 0.002
model_cfg:
  header_cfg:
    transop_header_cfg:
      batch_size: 256
      dictionary_size: 64
      lambda_prior: 0.01
      vi_cfg:
        enable_max_sampling: true
        max_sample_start_iter: 0
        samples_per_iter: 20
        total_num_samples: 20
        max_sample_l1_penalty: 0.0
        enable_prior_warmup: true
        prior_warmup_iters: 10000
  loss_cfg:
    ntxent_lie_temp: 0.5
    ntxent_lie_loss_mse: true
    enable_shift_l2: true
    enable_prior_shift_l2: false
    shift_l2_weight: 5.0e-3
    kl_weight_warmup: None