defaults:
  - transop_nn
  - _self_

exp_name: TransOp-VI-NN-Prediction

model_cfg:
  loss_cfg:
    kl_loss_weight: 1.0e-1
    real_eig_reg_active: false
  header_cfg:
    projection_type: Splicer
    projection_out_dim: 32
    lambda_prior: 0.04
    variational_inference_config:
      per_iter_samples: 1
      total_samples: 1
      use_warmpup: false
      normalize_coefficients: false
      normalize_mag: 1.0