defaults:
  - transop_cifar10_nn
  - _self_

exp_name: TransOp_NN_CIFAR10_DirectCLR

model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: DirectCLR
      projection_type: Direct