defaults:
  - transop_cifar10_simclr_laplacian
  - _self_

exp_name: vi-20s-40refine

trainer_cfg:
  num_epochs: 1000
  use_amp: false
model_cfg:
  loss_cfg:
    ntxent_loss_weight: 0.1
    kl_loss_weight: 1.0e-5
    kl_weight_warmup: Exponential
    transop_loss_weight: 1.0
    transop_loss_fn: mse
  backbone_cfg:
    load_backbone: /home/kion/manifold-contrastive/model_zoo/simclr_mlp.pt
  header_cfg:
    transop_header_cfg:
      start_iter: 0
      fine_tune_iter: 100000
      batch_size: 64
      vi_cfg:
        max_sample_start_iter: 0
        enable_enc_attn: false
        enable_learned_prior: true
        enable_prior_shift: true
        enable_fista_enc: true
        fista_lambda: 0.15
        enable_fista_var_reg: true
        fista_num_iters: 40