defaults:
  - base
  - _self_

exp_name: VICReg_CIFAR10
model_cfg:
  header_cfg:
    enable_projection_header: true
    projection_header_cfg:
      header_name: VICReg
      projection_type: MLP
      hidden_dim: 2048
      output_dim: 2048
  loss_cfg:
    ntxent_loss_active: false
    vicreg_loss_active: true
