dataset_cfg: 
  dataset_name: CIFAR10
  image_size: 64
collate_fn_cfg:
  collate_fn_type: LIGHTLY_IMAGE
  cj_prob: 0.5
  gausian_blur: 0.0
batch_size: 1024
train: true
shuffle: true
persistent_workers: true
num_workers: 8