dataset_cfg: 
  dataset_name: CIFAR100
  num_classes: 100
  image_size: 32
collate_fn_cfg:
  collate_fn_type: LIGHTLY_IMAGE
batch_size: 512
train: true
shuffle: true
persistent_workers: true
num_workers: 32