dataset_cfg: 
  dataset_name: ImageNet
  num_classes: 1000
  image_size: 224
  dataset_dir: ../../datasets/imagenet
collate_fn_cfg:
  collate_fn_type: LIGHTLY_IMAGE
  cj_bright: 0.8
  cj_contrast: 0.8
  cj_sat: 0.8
  cj_hue: 0.2
  min_scale: 0.08
  gausian_blur: 0.5
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
batch_size: 512
train: true
shuffle: true
persistent_workers: true
num_workers: 32