dataset_cfg: 
  dataset_name: STL10
  num_classes: 10
  image_size: 64
ssl_aug_cfg:
  normalize_mean: [0.43, 0.42, 0.39]
  normalize_std: [0.27, 0.26, 0.27]
persistent_workers: true
num_workers: 32
train_batch_size: 512