dataset_cfg: 
  dataset_name: TinyImageNet
  num_classes: 200
  image_size: 64
  dataset_dir: ../../datasets/tiny-imagenet-200
collate_fn_cfg:
  collate_fn_type: LIGHTLY_IMAGE
  normalize_mean: [0.480, 0.448, 0.398]
  normalize_std: [0.277, 0.269, 0.282]
batch_size: 512
train: true
shuffle: true
persistent_workers: true
num_workers: 32