defaults:
  - /exp_cfg/model_cfg/header_cfg/transop@_here_
  - _self_
header_name: TransOp
dictionary_size: 256
lambda_prior: 0.3
transop_weight_decay: 0.005
transop_lr: 0.001
detach_prediction: false
detach_feature: false
iter_variational_samples: 10
total_variational_samples: 50

use_warmpup: false
variational_scale_prior: 0.1
variational_feature_dim: 256
variational_encoder_lr: 0.0003
variational_encoder_weight_decay: 0.00001