defaults:
  - /exp_cfg/model_cfg/header_cfg/transop_header@_here_
  - _self_
header_name: TransOp
dictionary_size: 50
lambda_prior: 1.0
transop_weight_decay: 1.0e-5
transop_lr: 1.0e-4
detach_feature: false
iter_variational_samples: 5
total_variational_samples: 50

enable_variational_inference: true
use_warmpup: false
variational_use_features: true
use_ntxloss_sampling: false
variational_scale_prior: 0.5
variational_feature_dim: 128
variational_encoder_type: mlp
variational_encoder_lr: 1.0e-4
variational_encoder_weight_decay: 1.0e-5
projection_network_lr: 1.0e-4
projection_network_weight_decay: 1.0e-6