defaults:
  - /exp_cfg/model_cfg/header_cfg/transop_header@_here_
  - _self_
header_name: TransOp
dictionary_size: 200
lambda_prior: 0.04
transop_weight_decay: 1.0e-5
transop_lr: 1.0e-3
detach_feature: false
iter_variational_samples: 1
total_variational_samples: 1

enable_variational_inference: true
use_warmpup: false
variational_use_features: true
use_ntxloss_sampling: false
variational_scale_prior: 0.02
variational_feature_dim: 256
variational_encoder_type: mlp
variational_encoder_lr: 3.0e-4
variational_encoder_weight_decay: 1.0e-6
projection_network_lr: 1.0e-4
projection_network_weight_decay: 1.0e-6