defaults:
  - /exp_cfg/model_cfg/header_cfg/transop@_here_
  - _self_
header_name: TransOp
dictionary_size: 128
lambda_prior: 0.2
transop_weight_decay: 0.0005
transop_lr: 0.001
detach_prediction: false
detach_feature: false
iter_variational_samples: 4
total_variational_samples: 20

enable_variational_inference: true
use_warmpup: true
variational_use_features: true
use_ntxloss_sampling: false
variational_scale_prior: 0.1
variational_feature_dim: 512
variational_encoder_lr: 0.0003
variational_encoder_weight_decay: 0.00001