defaults:
  - /exp_cfg/model_cfg/header_cfg/transop_header@_here_
  - _self_
header_name: TransOp
dictionary_size: 200
lambda_prior: 0.04
transop_weight_decay: 1.0e-6
transop_lr: 1.0e-3
stable_operator_initialization: true
detach_feature: false

enable_variational_inference: true
vi_cfg:
  per_iter_samples: 10
  total_samples: 100
  use_warmpup: false
  encode_features: true
  ntxloss_sampling: false
  scale_prior: 0.02
  feature_dim: 256
  encoder_type: MLP
  variational_encoder_lr: 3.0e-4
  variational_encoder_weight_decay: 1.0e-5