defaults:
  - /exp_cfg/model_cfg/header_cfg/transop@_here_
  - _self_
header_name: TransOp
dictionary_size: 128
lambda_prior: 0.15
transop_weight_decay: 0.0001
num_coefficient_samples: 5

use_warmpup: false
variational_scale_prior: 0.1
variational_feature_dim: 256