defaults:
  - /exp_cfg/model_cfg/header_cfg/transop_header@_here_
  - _self_
header_name: TransOp
dictionary_size: 50
lambda_prior: 0.2
transop_weight_decay: 0.00001
transop_lr: 0.0001
detach_feature: false
iter_variational_samples: 1
total_variational_samples: 1

enable_variational_inference: true
use_warmpup: false
variational_use_features: true
use_ntxloss_sampling: false
variational_scale_prior: 0.1
variational_feature_dim: 512
variational_encoder_lr: 0.00005
variational_encoder_weight_decay: 0.000001