defaults:
  - /exp_cfg/model_cfg/header_cfg/transop@_here_
  - _self_
header_name: TransOp
dictionary_size: 128
lambda_prior: 1.2
transop_weight_decay: 0.02
transop_lr: 0.001
num_coefficient_samples: 5

use_warmpup: false
variational_scale_prior: 0.5
variational_feature_dim: 256